openapi: 3.0.3
info:
  title: ft_transcendence_api
  version: 0.0.1
  description: ft_transcendenceのバックエンドAPIドキュメント
servers:
  - url: http://localhost:3000
tags:
  - name: authentication
    description: 認証関連API
  - name: user
    description: ユーザー関連API
  - name: game
    description: ゲーム関連API

paths:
  /api/auth/login:
    post:
      tags:
        - authentication
      summary: ログイン/登録API
      description: 42アプリのcallbackに含まれるcodeを用いてログインまたは登録を行い、JWTトークンを発行します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: 42アプリのcallbackに含まれるcode
              required:
                - code
      responses:
        '200':
          description: 成功時、JWTトークンをhttpOnly cookieに設定します。


